Repository comfyanonymous/ComfyUI, pull requests merged in 2024-07, with the labels that each got.

#3792 enable cmd shortcuts for mac (mute & bypass)
  web/scripts/app.js
Labels: Feature, Frontend, Good PR

#3169 Fine-tuning GitHub Actions
  .github/workflows/windows_release_dependencies.yml
  .github/workflows/windows_release_nightly_pytorch.yml
  .github/workflows/windows_release_package.yml
Labels: Good PR

#3204 Fix several typos in example_node.py.example
  custom_nodes/example_node.py.example
Labels: documentation, Good PR

#3903 Add `--no-custom-node` cmd flag
  comfy/cli_args.py
  folder_paths.py
  main.py
  nodes.py
Labels: Feature

#3597 Add example for how to add custom API routes
  custom_nodes/example_node.py.example
Labels: documentation, Good PR

#3472 Fix to #3465. Prevent, resaving of duplicate images if overwrite not specified
  server.py
Labels: Feature, Good PR

#3932 fix non-contiguous tensor saving (from channels-last)
  comfy/sd.py
Labels: Bug, Good PR

#3976 Fix loadGraphData call during restore
  web/scripts/app.js
Labels: Good PR

#3897 Add `FrontendManager` to manage non-default front-end impl
  .github/workflows/test-ui.yaml
  .gitignore
  app/__init__.py
  app/frontend_management.py
  comfy/cli_args.py
  pytest.ini
  server.py
  tests-unit/README.md
  tests-unit/app_test/__init__.py
  tests-unit/app_test/frontend_manager_test.py
  tests-unit/requirements.txt
Labels: Feature

#3947 Make default hash lib configurable without code changes via CLI argument
  comfy/cli_args.py
  node_helpers.py
  server.py
Labels: Feature, Good PR

#4043 LoadAudio restores file value from workflow
  web/extensions/core/uploadAudio.js
Labels: Bug, Frontend

#4061 Fix/webp exif little endian
  web/scripts/pnginfo.js
Labels: Bug, Frontend

#4076 Add timestamp to execution messages
  execution.py
Labels: Feature

#4081 Add error message on unsupported control type in union controlnet
  comfy/cldm/cldm.py
  comfy/cldm/control_types.py
  comfy_extras/nodes_controlnet.py
Labels: Bug

#4114 Fix "undo" incorrectly undoing text input
  web/scripts/changeTracker.js
Labels: Bug, Frontend
