Repository comfyanonymous/ComfyUI, pull requests merged in 2024-12, with the labels that each got.

#5806 Add union link connection type support
  comfy_execution/validation.py
  execution.py
  tests-unit/execution_test/validate_node_input_test.py
Labels: Feature

#5889 Revert "Add union link connection type support"
  comfy_execution/validation.py
  execution.py
  tests-unit/execution_test/validate_node_input_test.py
Labels: Custom Nodes Bug

#5873 Add code owners
  CODEOWNERS
Labels: Important

#5973 Lint unused import
  .pylintrc
  comfy/cldm/cldm.py
  comfy/cldm/dit_embedder.py
  comfy/cldm/mmdit.py
  comfy/extra_samplers/uni_pc.py
  comfy/ldm/audio/autoencoder.py
  comfy/ldm/audio/embedders.py
  comfy/ldm/cascade/controlnet.py
  comfy/ldm/flux/controlnet.py
  comfy/ldm/genmo/joint_model/utils.py
  comfy/ldm/genmo/vae/model.py
  comfy/ldm/hydit/controlnet.py
  comfy/ldm/hydit/models.py
  comfy/ldm/hydit/poolers.py
  comfy/ldm/lightricks/vae/causal_video_autoencoder.py
  comfy/ldm/lightricks/vae/conv_nd_factory.py
  comfy/ldm/models/autoencoder.py
  comfy/ldm/modules/diffusionmodules/mmdit.py
  comfy/ldm/modules/diffusionmodules/model.py
  comfy/ldm/modules/diffusionmodules/openaimodel.py
  comfy/ldm/modules/diffusionmodules/upscaling.py
  comfy/ldm/modules/diffusionmodules/util.py
  comfy/ldm/modules/temporal_ae.py
  comfy/sampler_helpers.py
  comfy/text_encoders/spiece_tokenizer.py
  comfy_extras/nodes_advanced_samplers.py
  comfy_extras/nodes_clip_sdxl.py
  comfy_extras/nodes_compositing.py
  comfy_extras/nodes_hooks.py
  comfy_extras/nodes_model_advanced.py
  comfy_extras/nodes_model_downscale.py
  comfy_extras/nodes_upscale_model.py
  custom_nodes/websocket_image_save.py
  execution.py
  fix_torch.py
  folder_paths.py
  latent_preview.py
  main.py
  script_examples/basic_api_example.py
  tests/inference/test_inference.py
Labels: Run-CI-Test

#5841 Optimize model library
  app/model_manager.py
  server.py
Labels: Good PR, Important

#5989 Lint all unused variables
  .ci/update_windows/update.py
  comfy/cldm/cldm.py
  comfy/controlnet.py
  comfy/extra_samplers/uni_pc.py
  comfy/hooks.py
  comfy/k_diffusion/deis.py
  comfy/ldm/audio/dit.py
  comfy/ldm/aura/mmdit.py
  comfy/ldm/genmo/joint_model/asymm_models_joint.py
  comfy/ldm/hydit/controlnet.py
  comfy/ldm/hydit/models.py
  comfy/ldm/modules/attention.py
  comfy/ldm/modules/diffusionmodules/model.py
  comfy/ldm/util.py
  comfy/model_base.py
  comfy/model_detection.py
  comfy/model_management.py
  comfy/sampler_helpers.py
  comfy/samplers.py
  comfy/sd.py
  comfy/sd1_clip.py
  comfy/supported_models.py
  comfy/text_encoders/t5.py
  comfy_extras/nodes_hypertile.py
  comfy_extras/nodes_model_advanced.py
  fix_torch.py
  ruff.toml
  server.py
  tests/inference/testing_nodes/testing-pack/util.py
Labels: Run-CI-Test

#5564 add load 3d node support
  comfy_extras/nodes_load_3d.py
  nodes.py
Labels: Good PR, Important

#5998 add_model_folder_path: ensure unique paths by removing duplicates
  folder_paths.py
  tests-unit/comfy_test/folder_path_test.py
Labels: Important

#5872 fix: prestartup script is not applied due to `extra_model_paths.yaml` and ensure custom paths are used during startup
  main.py
Labels: Run-CI-Test, Important

#6137 remove minimum step count for AYS
  comfy_extras/nodes_align_your_steps.py
Labels: Good PR

#6243 Add option to log non-error output to stdout
  app/logger.py
  comfy/cli_args.py
  main.py
Labels: Good PR

#6193 serve workflow templates from custom_nodes
  app/custom_node_manager.py
  nodes.py
  server.py
  tests-unit/app_test/custom_node_manager_test.py
Labels: Good PR, Important

#6249 Remove duplicate calls to INPUT_TYPES
  comfy_execution/graph.py
  execution.py
Labels: Good PR, Important, Performance

#6206 Add kl_optimal scheduler
  comfy/samplers.py
Labels: Good PR

#6280 Fix unknown scheduler error handling in calculate_sigmas function
  comfy/samplers.py
Labels: Run-CI-Test
