Repository comfyanonymous/ComfyUI, pull requests merged in 2024-10, with the labels that each got.

#5191 Increase maximum macOS version to 15.0.1 when forcing upcast attention
  comfy/model_management.py
Labels: Run-CI-Test

#5140 Fix Transformers FutureWarning
  comfy/sd1_clip.py
Labels: Run-CI-Test

#5152 Frontend Manager: avoid redundant gh calls for static versions
  app/frontend_management.py
Labels: Bug, Good PR

#5269 Ignore more network related errors during websocket communication.
  server.py
Labels: Run-CI-Test

#5424 Rename `ImageCrop` to `Image Crop`
  nodes.py
Labels: Good PR

#5442 Avoid SyntaxWarning in UniPC docstring
  comfy/extra_samplers/uni_pc.py
Labels: Good PR
