Repository comfyanonymous/ComfyUI, pull requests merged in 2024-08, with the labels that each got.

#4158 Lower SAG scale step for finer control
  comfy_extras/nodes_pag.py
  comfy_extras/nodes_sag.py
Labels: Feature, Good PR

#4200 Correct spelling 'token_weight_pars_t5' to 'token_weight_pairs_t5'
  comfy/text_encoders/flux.py
  comfy/text_encoders/sd3_clip.py
Labels: Good PR

#4191 Add type hints to folder_paths.py
  folder_paths.py
Labels: Good PR

#4274 Add full CI test matrix GitHub Workflow
  .github/workflows/test-ci.yml
Labels: Feature, Good PR, Developer Experience

#4245 feat: add support for HunYuanDit ControlNet
  comfy/controlnet.py
  comfy/ldm/hydit/controlnet.py
  comfy/ldm/hydit/models.py
  comfy_extras/nodes_hunyuan.py
Labels: Run-CI-Test

#4326 Automatically link the Comfy CI page on PRs
  .github/workflows/pullrequest-ci-run.yml
Labels: Feature, Good PR

#4324 Add `DS_Store` to gitignore
  .gitignore
Labels: Good PR

#4260 xlabs Flux controlnet implementation.
  comfy/controlnet.py
  comfy/ldm/flux/controlnet_xlabs.py
  comfy/ldm/flux/model.py
Labels: Run-CI-Test

#3842 Add support for simple tooltips
  nodes.py
  server.py
  web/extensions/core/tooltips.js
  web/extensions/core/widgetInputs.js
  web/scripts/app.js
  web/scripts/domWidget.js
  web/scripts/widgets.js
  web/style.css
Labels: Feature, Frontend

#2666 Execution Model Inversion
  comfy/caching.py
  comfy/cli_args.py
  comfy/graph.py
  comfy/graph_utils.py
  custom_nodes/example_node.py.example
  execution.py
  main.py
  pytest.ini
  server.py
  tests/inference/extra_model_paths.yaml
  tests/inference/test_execution.py
  tests/inference/testing_nodes/testing-pack/__init__.py
  tests/inference/testing_nodes/testing-pack/conditions.py
  tests/inference/testing_nodes/testing-pack/flow_control.py
  tests/inference/testing_nodes/testing-pack/specific_tests.py
  tests/inference/testing_nodes/testing-pack/stubs.py
  tests/inference/testing_nodes/testing-pack/tools.py
  tests/inference/testing_nodes/testing-pack/util.py
  web/extensions/core/groupNode.js
  web/extensions/core/widgetInputs.js
  web/scripts/api.js
  web/scripts/app.js
  web/scripts/ui.js
Labels: Run-CI-Test

#4295 Add GET /internal/files.
  api_server/__init__.py
  api_server/routes/__init__.py
  api_server/routes/internal/README.md
  api_server/routes/internal/__init__.py
  api_server/routes/internal/internal_routes.py
  api_server/services/__init__.py
  api_server/services/file_service.py
  api_server/utils/file_operations.py
  server.py
  tests-unit/server/routes/internal_routes_test.py
  tests-unit/server/services/file_service_test.py
  tests-unit/server/utils/file_operations_test.py
Labels: Feature

#4519 add a get models list api route
  server.py
Labels: Feature, Good PR

#4535 Fix a bug where cached outputs affected IS_CHANGED
  execution.py
  tests/inference/test_execution.py
  tests/inference/testing_nodes/testing-pack/specific_tests.py
  tests/inference/testing_nodes/testing-pack/stubs.py
Labels: Bug, Good PR

#4576 Support weight padding on diff weight patch
  comfy/lora.py
Labels: Run-CI-Test

#4683 add github action to automatically handle stale user support issues
  .github/workflows/stale-issues.yml
Labels: Feature, Good PR
