Repository comfyanonymous/ComfyUI, pull requests merged in 2024-09, with the labels that each got.

#4735 fix typo in stale-issues
  .github/workflows/stale-issues.yml
Labels: Good PR

#4649 Make live preview size a configurable launch argument
  comfy/cli_args.py
  latent_preview.py
Labels: Good PR

#4030 allow current timestamp in save image prefix
  folder_paths.py
Labels: Feature, Good PR

#4756 Add .venv to gitignore
  .gitignore
Labels: Good PR

#4054 Add content-type filter method to folder_paths
  comfy_extras/nodes_audio.py
  folder_paths.py
  tests-unit/folder_paths_test/__init__.py
  tests-unit/folder_paths_test/filter_by_content_types_test.py
Labels: Good PR

#3871 Add CFG++ to DPM++ 2S Ancestral
  comfy/k_diffusion/sampling.py
  comfy/samplers.py
Labels: Feature, Good PR

#4871 Reduce repeated calls of get_immediate_node_signature in cache
  comfy_execution/caching.py
Labels: Run-CI-Test

#4886 Fix RecursionError for (very) large graphs
  comfy_execution/graph.py
Labels: Run-CI-Test

#4922 Reduce repeated calls of INPUT_TYPES in cache
  comfy_execution/caching.py
Labels: Run-CI-Test

#4950 add simple error check to model loading
  comfy_extras/nodes_hypernetwork.py
  comfy_extras/nodes_photomaker.py
  comfy_extras/nodes_sd3.py
  comfy_extras/nodes_upscale_model.py
  comfy_extras/nodes_video_model.py
  folder_paths.py
  nodes.py
Labels: Good PR

#4846 Add route to list model types
  server.py
Labels: Feature, Good PR

#4981 Internal download API: Add proper validated directory input
  model_filemanager/__init__.py
  model_filemanager/download_models.py
  server.py
  tests-unit/prompt_server_test/download_models_test.py
Labels: Feature, Good PR
