Repository comfyanonymous/ComfyUI, pull requests merged in 2025-04, with the labels that each got.

#7439 User missing
  app/app_settings.py
Labels: Good PR, Important

#7482 Add activations_shape info in UNet models
  comfy/ldm/modules/attention.py
Labels: Good PR

#7423 Align /prompt response schema
  execution.py
  server.py
Labels: Important

#7551 Deprecate InputTypeOptions.defaultInput
  comfy/comfy_types/node_typing.py
Labels: documentation, Important

#7564 Update frontend to 1.15
  requirements.txt
Labels: Frontend, Important, dependencies

#7572 Update `filter_files_content_types` to support filtering 3d models
  folder_paths.py
  tests-unit/folder_paths_test/filter_by_content_types_test.py
Labels: Important

#7614 [Type] Mark input options NotRequired
  comfy/comfy_types/node_typing.py
Labels: documentation, Important

#7623 Update frontend to 1.16 (Install templates as pip package)
  app/frontend_management.py
  requirements.txt
  server.py
Labels: Frontend, Important, dependencies

#7386 [Type] Annotate graph.get_input_info
  comfy_execution/graph.py
  execution.py
Labels: Important

#7582 add support to output camera state
  comfy_extras/nodes_load_3d.py
Labels: Important

#7655 [BugFix] Update frontend to 1.16.9
  requirements.txt
Labels: Frontend, dependencies, Core-Important

#7678 Add wanfun template workflows.
  requirements.txt
Labels: Core

#7663 Update CODEOWNERS and add christian-byrne
  CODEOWNERS
Labels: Core

#7709 Populate AUTH_TOKEN_COMFY_ORG hidden input
  execution.py
Labels: Core-Important

#7714 Add node type hint for socketless option
  comfy/comfy_types/node_typing.py
Labels: documentation, Core

#7540 Unified Weight Adapter system for better maintainability and future feature of Lora system
  comfy/lora.py
  comfy/weight_adapter/__init__.py
  comfy/weight_adapter/base.py
  comfy/weight_adapter/glora.py
  comfy/weight_adapter/loha.py
  comfy/weight_adapter/lokr.py
  comfy/weight_adapter/lora.py
Labels: Important

#7762 [BugFix] Update frontend to 1.17.10
  requirements.txt
Labels: Frontend, dependencies, Core-Important

#7765 change timeout to 7 days because there's no reason to actually timeout eagerly
  comfy_api_nodes/apis/client.py
Labels: Core-Important

#7766 [BugFix] Update frontend to 1.17.11
  requirements.txt
Labels: Frontend, dependencies, Core-Important

#7768 [NodeDef] Add documentation on widgetType
  comfy/comfy_types/node_typing.py
Labels: documentation

#7817 Add `/api/v2/userdata` endpoint
  app/user_manager.py
  tests-unit/prompt_server_test/user_manager_test.py
Labels: Core

#7844 Add support for VIDEO as a built-in type
  comfy/comfy_types/node_typing.py
  comfy_api/input/__init__.py
  comfy_api/input/basic_types.py
  comfy_api/input/video_types.py
  comfy_api/input_impl/__init__.py
  comfy_api/input_impl/video_types.py
  comfy_api/util/__init__.py
  comfy_api/util/video_types.py
  comfy_extras/nodes_video.py
  folder_paths.py
Labels: Core-Important, Core

#7855 Add release process section to README
  README.md
Labels: documentation
