Repository comfyanonymous/ComfyUI, pull requests merged in 2025-10, with the labels that each got.

#10123 [V3] convert nodes_audio_encoder.py to V3 schema
  comfy_api/latest/_io.py
  comfy_extras/nodes_audio_encoder.py
Labels: Core

#9949 [V3] convert nodes_gits.py to V3 schema
  comfy_extras/nodes_gits.py
Labels: Core, Awaiting Merge

#10074 [V3] convert nodes_optimalsteps.py to V3 schema
  comfy_extras/nodes_optimalsteps.py
Labels: Core, Awaiting Merge

#10080 [V3] convert nodes_pag.py to V3 schema
  comfy_extras/nodes_pag.py
Labels: Core, Awaiting Merge

#10084 [V3] convert nodes_lt.py to V3 schema
  comfy_extras/nodes_lt.py
Labels: Core, Awaiting Merge

#10132 feat: Add Epsilon Scaling node for exposure bias correction
  comfy_extras/nodes_eps.py
  nodes.py
Labels: Good PR

#10139 sd: fix VAE tiled fallback VRAM leak
  comfy/sd.py
Labels: Good PR

#10141 WAN VAE: Fix cache VRAM leak on error
  comfy/ldm/wan/vae.py
Labels: Good PR

#9723 [V3] update example_node.py to use V3 schema
  custom_nodes/example_node.py.example
Labels: Core

#10155 feat(api-nodes): add kling-2-5-turbo to txt2video and img2video nodes
  comfy_api_nodes/apis/__init__.py
  comfy_api_nodes/nodes_kling.py
Labels: Core, Requires QA

#10175 fix(api-nodes): bad indentation in Recraft API node function
  comfy_api_nodes/nodes_recraft.py
  pyproject.toml
Labels: Core

#10173 [V3] convert nodes_torch_compile.py to V3 schema
  comfy_extras/nodes_torch_compile.py
Labels: Core

#10195 [V3] convert nodes_rodin.py to V3 schema
  comfy_api_nodes/nodes_rodin.py
Labels: Core

#10204 [V3] convert nodes_stable3d.py to V3 schema
  comfy_extras/nodes_stable3d.py
Labels: Core

#10196 fix(api-nodes): allow negative_prompt in PixVerse API nodes to be multiline
  comfy_api_nodes/nodes_pixverse.py
Labels: Core

#10236 [V3] convert nodes_kling.py to V3 schema
  comfy_api_nodes/nodes_kling.py
Labels: Core

#10237 feat(V3-io): allow Enum classes for Combo options
  comfy_api/latest/_io.py
  comfy_api_nodes/nodes_bytedance.py
  comfy_api_nodes/nodes_kling.py
  comfy_api_nodes/nodes_luma.py
  comfy_api_nodes/nodes_pika.py
  comfy_api_nodes/nodes_pixverse.py
  comfy_api_nodes/nodes_runway.py
  comfy_api_nodes/nodes_stability.py
  comfy_api_nodes/nodes_vidu.py
Labels: v3
