Repository comfyanonymous/ComfyUI, pull requests merged in 2025-08, with the labels that each got.

#9110 Add Veo3 video generation node with audio support
  .gitattributes
  comfy_api_nodes/apis/__init__.py
  comfy_api_nodes/apis/tripo_api.py
  comfy_api_nodes/nodes_veo2.py
Labels: Core-Important

#9234 _ui.py import torchaudio safety check
  comfy_api/latest/_ui.py
Labels: Core

#9284 remove creation of non-used asyncio_loop
  execution.py
Labels: Good PR, Run-CI-Test

#9309 Make torchaudio exception catching less specific
  comfy_api/latest/_ui.py
Labels: Core

#9238 Added context window support to core sampling code
  comfy/context_windows.py
  comfy/sampler_helpers.py
  comfy/samplers.py
  comfy_extras/nodes_context_windows.py
  nodes.py
Labels: Core

#9343 Update CODEOWNERS
  CODEOWNERS
Labels: Core-Important

#9290 Update default parameters for Moonvalley video nodes
  comfy_api_nodes/nodes_moonvalley.py
Labels: Core

#9201 convert WAN nodes to V3 schema
  comfy_extras/nodes_wan.py
Labels: Core, v3

#9392 Make context step index detection much more robust
  comfy/context_windows.py
Labels: Core

#9412 P2 of qwen edit model.
  comfy/clip_model.py
  comfy/model_base.py
  comfy/sd1_clip.py
  comfy/text_encoders/bert.py
  comfy/text_encoders/llama.py
  comfy/text_encoders/qwen_image.py
  comfy/text_encoders/qwen_vl.py
  comfy/text_encoders/t5.py
  comfy_extras/nodes_qwen.py
  nodes.py
Labels: Run-CI-Test

#9257 api_nodes: add kling-v2-1 and v2-1-master
  comfy_api_nodes/apis/__init__.py
  comfy_api_nodes/nodes_kling.py
Labels: Core

#9325 api_nodes: add GPT-5 series models
  comfy_api_nodes/nodes_openai.py
Labels: Core

#9465 Support for Qwen Diffsynth Controlnets canny and depth.
  comfy/ldm/qwen_image/model.py
  comfy/model_management.py
  comfy/model_patcher.py
  comfy_api/latest/_io.py
  comfy_extras/nodes_model_patch.py
  models/model_patches/put_model_patches_here
  nodes.py
Labels: Run-CI-Test

#9149 v3 nodes (part a)
  comfy_extras/nodes_ace.py
  comfy_extras/nodes_advanced_samplers.py
  comfy_extras/nodes_apg.py
  comfy_extras/nodes_attention_multiply.py
Labels: Core, v3

#9278 [V3] convert Ideogram API nodes to the V3 schema
  comfy_api_nodes/nodes_ideogram.py
Labels: Core, v3

#9443 feat(api-nodes): change "OpenAI Chat" display name to "OpenAI ChatGPT"
  comfy_api_nodes/nodes_openai.py
Labels: Core-Important

#9566 Adding Google Gemini Image API node
  comfy_api_nodes/apis/gemini_api.py
  comfy_api_nodes/nodes_gemini.py
  requirements.txt
Labels: Core-Important, Core

#9489 [V3] convert Video nodes to V3 schema
  comfy_extras/nodes_video.py
Labels: v3

#9497 [V3] convert nodes_stability.py to V3 schema
  comfy_api_nodes/nodes_stability.py
Labels: Core, v3

#9372 convert Primitive nodes to V3 schema
  comfy_extras/nodes_primitive.py
Labels: Core, v3
