Repository comfyanonymous/ComfyUI, pull requests merged in 2025-01, with the labels that each got.

#6357 Document get_attr and get_model_object
  comfy/model_patcher.py
  comfy/utils.py
Labels: documentation

#6386 Add pyproject.toml
  .github/workflows/update-version.yml
  comfyui_version.py
  pyproject.toml
  server.py
Labels: Developer Experience

#6431 Merge ruff.toml into pyproject.toml
  pyproject.toml
  ruff.toml
Labels: Developer Experience

#6558 [i18n] Add /i18n endpoint to provide all custom node translations
  app/custom_node_manager.py
  tests-unit/app_test/custom_node_manager_test.py
  tests-unit/utils/json_util_test.py
  utils/json_util.py
Labels: Frontend, Important

#6600 Allow changing folder_paths.base_path via command line argument.
  comfy/cli_args.py
  folder_paths.py
  tests-unit/comfy_test/folder_path_test.py
Labels: Good PR
