Repository comfyanonymous/ComfyUI, pull requests merged in 2025-09, with the labels that each got.

#9607 Accept prompt_id in interrupt handler
  server.py
Labels: Core-Important, Core

#9477 feat(api-nodes): add ByteDance Image nodes
  comfy_api_nodes/nodes_bytedance.py
  nodes.py
Labels: Core-Important

#9487 [V3] convert Runway API nodes to the V3 schema
  comfy_api_nodes/nodes_runway.py
Labels: Core, v3

#9226 convert AlignYourStepsScheduler node to V3 schema
  comfy_extras/nodes_align_your_steps.py
Labels: Core

#9706 Fix progress update crossover between users
  .github/workflows/test-execution.yml
  comfy_execution/progress.py
  tests/conftest.py
  tests/execution/extra_model_paths.yaml
  tests/execution/test_async_nodes.py
  tests/execution/test_execution.py
  tests/execution/test_progress_isolation.py
  tests/execution/testing_nodes/testing-pack/__init__.py
  tests/execution/testing_nodes/testing-pack/api_test_nodes.py
  tests/execution/testing_nodes/testing-pack/async_test_nodes.py
  tests/execution/testing_nodes/testing-pack/conditions.py
  tests/execution/testing_nodes/testing-pack/flow_control.py
  tests/execution/testing_nodes/testing-pack/specific_tests.py
  tests/execution/testing_nodes/testing-pack/stubs.py
  tests/execution/testing_nodes/testing-pack/tools.py
  tests/execution/testing_nodes/testing-pack/util.py
Labels: Core

#9712 API nodes: add ByteDance video
  comfy_api_nodes/nodes_bytedance.py
Labels: Core

#9932 Fix image sharpen node
  comfy_extras/nodes_post_processing.py
Labels: Good PR

#9918 fix(api_nodes): reduce default timeout from 7 days to 2 hours
  comfy_api_nodes/apis/client.py
Labels: Core

#9957 [Reviving #5709] Add strength input to Differential Diffusion
  comfy_extras/nodes_differential_diffusion.py
Labels: Core

#9854 Fix LoRA Trainer bugs with FP8 models.
  comfy/ops.py
  comfy/weight_adapter/loha.py
  comfy/weight_adapter/lokr.py
  comfy/weight_adapter/lora.py
  comfy/weight_adapter/oft.py
  comfy_extras/nodes_train.py
Labels: Core

#9908 Add new audio nodes
  comfy_extras/nodes_audio.py
Labels: Core

#9491 [V3] convert nodes_post_processing to V3 schema
  comfy_extras/nodes_post_processing.py
Labels: Core

#9716 [V3] convert CLIPTextEncodeSDXL nodes to V3 schema
  comfy_extras/nodes_clip_sdxl.py
Labels: Core

#10033 [V3] convert nodes_bfl.py to V3 schema
  comfy_api_nodes/nodes_bfl.py
Labels: Core

#10030 [V3] convert nodes_luma.py to V3 schema
  comfy_api_nodes/nodes_luma.py
Labels: Core

#10019 [V3] convert nodes_pixart.py to V3 schema
  comfy_extras/nodes_pixart.py
Labels: Core

#10017 [V3] convert nodes_photomaker.py to V3 schema
  comfy_extras/nodes_photomaker.py
Labels: Core

#10049 [V3] convert nodes_qwen.py to V3 schema
  comfy_extras/nodes_qwen.py
Labels: Core

#10057 [V3] convert nodes_lotus.py to V3 schema
  comfy_extras/nodes_lotus.py
Labels: Core

#10058 [V3] convert nodes_lumina2.py to V3 schema
  comfy_extras/nodes_lumina2.py
Labels: Core

#10061 [V3] convert nodes_hypertile.py to V3 schema
  comfy_extras/nodes_hypertile.py
Labels: Core

#10094 feat(api-nodes): add WanImageToImageApi node
  comfy_api_nodes/nodes_wan.py
Labels: Core

#10069 [V3] convert nodes_mochi.py to V3 schema
  comfy_extras/nodes_mochi.py
Labels: Core

#10081 [V3] convert nodes_perpneg.py to V3 schema
  comfy_extras/nodes_perpneg.py
Labels: Core

#10120 feat(api-nodes): enable Seedance Pro model in the FirstLastFrame node
  comfy_api_nodes/nodes_bytedance.py
Labels: Core
