Repository comfyanonymous/ComfyUI, pull requests merged in 2025-03, with the labels that each got.

#7059 [NodeDef] Explicitly add control_after_generate to seed/noise_seed
  comfy/comfy_types/node_typing.py
  comfy_extras/nodes_custom_sampler.py
  nodes.py
Labels: Important

#7043 Better argument handling of front-end-root
  comfy/cli_args.py
Labels: Important

#6968 Add type hint for FileLocator
  comfy/comfy_types/__init__.py
  comfy/comfy_types/node_typing.py
  comfy_extras/nodes_audio.py
  comfy_extras/nodes_images.py
  comfy_extras/nodes_video.py
  nodes.py
Labels: Important

#7119 Update frontend to 1.11.8
  requirements.txt
Labels: Frontend, Important, dependencies

#6931 [3d] remove unused params
  comfy_extras/nodes_load_3d.py
Labels: Frontend, Important

#7179 Only check frontend package if using default frontend
  app/frontend_management.py
  main.py
  tests-unit/app_test/frontend_manager_test.py
Labels: Frontend, Important, dependencies

#7143 Fix LoadImageOutput node
  nodes.py
Labels: Important

#7197 Add unwrap widget value support
  execution.py
Labels: Important

#7212 [NodeDef] Add documentation on multi_select input option
  comfy/comfy_types/node_typing.py
Labels: Important

#7343 Update frontend to 1.14
  requirements.txt
Labels: Frontend, dependencies

#7290 support output normal and lineart once
  comfy_extras/nodes_load_3d.py
Labels: Frontend, Important

#7416 Update frontend to 1.14.6
  requirements.txt
Labels: Frontend, Important, dependencies
