Repository comfyanonymous/ComfyUI, pull requests merged in 2025-05, with the labels that each got.

#7355 Support for Chroma - Flux1 Schnell distilled with CFG
  comfy/ldm/chroma/layers.py
  comfy/ldm/chroma/math.py
  comfy/ldm/chroma/model.py
  comfy/lora.py
  comfy/model_base.py
  comfy/model_detection.py
  comfy/sd.py
  comfy/supported_models.py
  comfy/text_encoders/chroma.py
  comfy_extras/nodes_optimalsteps.py
  nodes.py
Labels: Important

#7898 Update frontend to v1.18
  requirements.txt
Labels: Frontend, dependencies, Core-Important

#7827 Fix outdated comment about Internet connectivity
  main.py
Labels: documentation, Good PR

#7815 upstream Preview Any from rgthree-comfy
  comfy_extras/nodes_preview_any.py
  nodes.py
Labels: Core-Important, Core

#7956 More API nodes
  .github/workflows/test-launch.yml
  .github/workflows/update-api-stubs.yml
  .gitignore
  comfy/cli_args.py
  comfy_api_nodes/README.md
  comfy_api_nodes/apinode_utils.py
  comfy_api_nodes/apis/PixverseController.py
  comfy_api_nodes/apis/PixverseDto.py
  comfy_api_nodes/apis/__init__.py
  comfy_api_nodes/apis/bfl_api.py
  comfy_api_nodes/apis/client.py
  comfy_api_nodes/apis/luma_api.py
  comfy_api_nodes/apis/pixverse_api.py
  comfy_api_nodes/apis/recraft_api.py
  comfy_api_nodes/apis/stability_api.py
  comfy_api_nodes/mapper_utils.py
  comfy_api_nodes/nodes_api.py
  comfy_api_nodes/nodes_bfl.py
  comfy_api_nodes/nodes_ideogram.py
  comfy_api_nodes/nodes_kling.py
  comfy_api_nodes/nodes_luma.py
  comfy_api_nodes/nodes_minimax.py
  comfy_api_nodes/nodes_openai.py
  comfy_api_nodes/nodes_pika.py
  comfy_api_nodes/nodes_pixverse.py
  comfy_api_nodes/nodes_recraft.py
  comfy_api_nodes/nodes_stability.py
  comfy_api_nodes/nodes_veo2.py
  comfy_api_nodes/redocly-dev.yaml
  comfy_api_nodes/redocly.yaml
  comfy_extras/nodes_primitive.py
  nodes.py
  requirements.txt
  tests-unit/comfy_api_nodes_test/mapper_utils_test.py
Labels: Run-CI-Test

#7972 Initial ACE-Step model implementation.
  comfy/latent_formats.py
  comfy/ldm/ace/attention.py
  comfy/ldm/ace/lyric_encoder.py
  comfy/ldm/ace/model.py
  comfy/ldm/ace/vae/autoencoder_dc.py
  comfy/ldm/ace/vae/music_dcae_pipeline.py
  comfy/ldm/ace/vae/music_log_mel.py
  comfy/ldm/ace/vae/music_vocoder.py
  comfy/model_base.py
  comfy/model_detection.py
  comfy/sd.py
  comfy/supported_models.py
  comfy/text_encoders/ace.py
  comfy/text_encoders/ace_lyrics_tokenizer/vocab.json
  comfy/text_encoders/ace_text_cleaners.py
  comfy/text_encoders/umt5_config_base.json
  comfy_extras/nodes_ace.py
  nodes.py
Labels: Run-CI-Test

#7982 move SVG to core
  comfy_api_nodes/apis/recraft_api.py
  comfy_api_nodes/nodes_recraft.py
  comfy_extras/nodes_images.py
Labels: Core

#8041 Add support for Comfy API keys
  comfy_api_nodes/apinode_utils.py
  comfy_api_nodes/apis/client.py
  comfy_api_nodes/nodes_bfl.py
  comfy_api_nodes/nodes_ideogram.py
  comfy_api_nodes/nodes_kling.py
  comfy_api_nodes/nodes_luma.py
  comfy_api_nodes/nodes_minimax.py
  comfy_api_nodes/nodes_openai.py
  comfy_api_nodes/nodes_pika.py
  comfy_api_nodes/nodes_pixverse.py
  comfy_api_nodes/nodes_recraft.py
  comfy_api_nodes/nodes_stability.py
  comfy_api_nodes/nodes_veo2.py
  execution.py
  requirements.txt
Labels: Run-CI-Test

#7952 Add nodes for basic string operations
  comfy_extras/nodes_string.py
  nodes.py
Labels: Core

#8076 Update frontend to v1.19
  requirements.txt
Labels: Frontend, dependencies, Core-Important

#7927 add support to record video as output for 3d node
  comfy_extras/nodes_load_3d.py
Labels: Core

#7988 rework client.py to be more robust, add logging of api requests
  comfy_api_nodes/apis/client.py
  comfy_api_nodes/apis/request_logger.py
Labels: Core

#8232 Update frontend to 1.20
  requirements.txt
Labels: Frontend, dependencies, Core-Important

#8337 Cleanup BFL API nodes for Kontext [pro] and [max]
  comfy_api_nodes/apis/bfl_api.py
  comfy_api_nodes/nodes_bfl.py
Labels: Core
