Repository comfyanonymous/ComfyUI, pull requests merged in 2025-02, with the labels that each got.

#6689 Allow searching for .pt2 archives
  folder_paths.py
Labels: Good PR

#6542 Fix for running via DirectML
  comfy/clip_model.py
  comfy/ldm/flux/math.py
  comfy/model_management.py
Labels: AMD

#6742 remove light_intensity and fov from load3d
  comfy_extras/nodes_load_3d.py
Labels: Important

#6790 Add Load Image Output node
  api_server/routes/internal/internal_routes.py
  comfy/comfy_types/node_typing.py
  nodes.py
Labels: Feature, Important
