Repository comfyanonymous/ComfyUI, pull requests merged in 2025-06, with the labels that each got.

#8179 Add Help Menu in NodeLibrarySidebarTab
  app/frontend_management.py
  requirements.txt
  server.py
Labels: Core-Important, Core

#8382 [BugFix] Update frontend to 1.21.5
  requirements.txt
Labels: Frontend, dependencies, Core-Important

#8446 LoRA Trainer: LoRA training node in weight adapter scheme
  comfy/comfy_types/node_typing.py
  comfy/ldm/modules/attention.py
  comfy/model_patcher.py
  comfy/sd.py
  comfy/weight_adapter/__init__.py
  comfy/weight_adapter/base.py
  comfy/weight_adapter/lora.py
  comfy_extras/nodes_train.py
  execution.py
  folder_paths.py
  nodes.py
  tests-unit/folder_paths_test/misc_test.py
Labels: Run-CI-Test, Core

#8507 Add new fields to the config types
  comfy_config/config_parser.py
  comfy_config/types.py
Labels: Good PR, Core-Important, Core

#6207 Improve the log time function for 10 minute + renders
  main.py
Labels: Good PR

#8652 [System Pop Up] Add GitHub Action for release webhook notifications
  .github/workflows/release-webhook.yml
Labels: Core-Important

#8724 V3 definition update - Resource management + Preview helper
  comfy_api/v3/io.py
  comfy_api/v3/resources.py
  comfy_api/v3/ui.py
  comfy_extras/nodes_v3_test.py
  execution.py
Labels: v3
